### ISSUE TITLE
Use /locraw instead of the hypixel API to get the current mode

### ISSUE THREAD

**Issue by Prorok5247** [HumanDuck23/virtual-hypixel-v4#11]
When I first tried to get the stats of the person I was currently queueing, nothing came up. After a stupid amount of time I figured out it was because of the API settings that were disabled on my profile. I suggest you use /locraw instead of the API so other people that have those settings disabled don't into the same issue. /locraw contains a lot of useful information and you could also use it instead of /whereami to see if the playing is currently in-game.

Also image of the data you can get by using /locraw:

![image](https://user-images.githubusercontent.com/49730904/161601548-1f348520-d218-4933-87f2-f942d4b77052.png)

**Comment by HumanDuck23** [comment]
Ohh i had no idea locraw also sent the mode, good idea (might also solve some other issues with api ratelimits)
Thanks for this, gonna implement it later today.

**Comment by HumanDuck23** [comment]
added in commit 71dc40b.
