### ISSUE TITLE
Type 'AbortSignal' is not assignable to type

### ISSUE THREAD

**Issue by sanjerno** [HumanDuck23/virtual-hypixel-v4#12]
When I followed step 9 and typed tsc in CMD it threw these errors at me with no discernible reason. 
I followed all previous instructions up to this and they all worked fine, if this is a mistake on my part I am quite sorry.

![Screenshot 2022-08-23 111304](https://user-images.githubusercontent.com/91035826/186208771-7c35cd8e-df92-4241-af4e-0e33af6cf512.png)

**Comment by JosTheDude** [comment]
Hey! These errors have no effect on the proxy (as per my research) and can be ignored safely without any issue, just continue to follow the setup steps and start the proxy as normal and it should be fine.

Thanks for using Virtual Hypixel v4!

**Comment by JosTheDude** [comment]
_@HumanDuck23 when close_

**Comment by HumanDuck23** [comment]
whoops
