### ISSUE TITLE
Players dissapear

### ISSUE THREAD

**Issue by BaldSussyEgg** [HumanDuck23/virtual-hypixel-v4#14]
Players fully dissapear after the game start in duels (Classic duels)

**Comment by BaldSussyEgg** [comment]
*Figured out how to fix: Disable the true nick & true skin show

**Comment by HumanDuck23** [comment]
thanks for pointing it out, if I pick this project up again I'll try and properly implement that feature because it's always been super buggy.

**Comment by JosTheDude** [comment]
Sphaget is alive? No way
