### ISSUE TITLE
Ranked Tourney Fricks Tab w/ Stats Check

### ISSUE THREAD

**Issue by JosTheDude** [HumanDuck23/virtual-hypixel-v4#3]
![image](https://user-images.githubusercontent.com/43651265/159095072-8e7390f1-cba2-4287-907c-d63052157599.png)
Image Attached (title)

**Comment by HumanDuck23** [comment]
This is because the proxy sends the correct name and skin of players in a mode where they are hidden (duels, tourney) and doesn't remove them again. Will work on this soon

**Comment by HumanDuck23** [comment]
Should be fixed now, no way to test outside of duels but we can reopen the issue if it still breaks in the next tourney.
